name: Raghav Rathi Workflow
on:
  workflow_dispatch:

jobs:
  greeting-job:
    name: Raghav Rathi Job
    runs-on: ubuntu-latest
    steps:
      - name: Personal Greeting
        run: echo "Hello Raghav Rathi! Hello bhai mere!"
      - name: Show date
        run: date
      - name: Show operating system
        run: uname -a
